name: Regression Tests

on: [push, pull_request]

jobs:
  build:
    name: Python ${{matrix.python-version}}
    # swapped to macos for now since iverilog11 is installed by default there
    runs-on: macos-10.15

    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: Install Icarus Verilog
      run: |
        brew install icarus-verilog

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox